# Generated by Django 4.2.16 on 2025-01-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_osoba_options_alter_stanowisko_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produkt',
        ),
    ]
