# Generated by Django 4.2.16 on 2025-01-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_osoba_plec'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='pseudonim',
            field=models.CharField(default='', max_length=100),
        ),
    ]
