# Generated by Django 4.2.16 on 2025-01-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_osoba_pseudonim'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='miesiac',
            field=models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=1),
        ),
    ]
