# Generated by Django 5.1.5 on 2025-01-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='stanowisko',
        ),
        migrations.DeleteModel(
            name='Produkt',
        ),
        migrations.DeleteModel(
            name='Osoba',
        ),
        migrations.DeleteModel(
            name='Stanowisko',
        ),
    ]
