# Generated by Django 4.2.16 on 2025-01-15 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_product_produkt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkt',
            options={'verbose_name_plural': 'Produkty'},
        ),
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
