# Generated by Django 5.1.4 on 2024-12-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_osoba_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterModelOptions(
            name='stanowisko',
            options={'verbose_name': 'Stanowisko', 'verbose_name_plural': 'Stanowiska'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Drużyna', 'verbose_name_plural': 'Drużyny'},
        ),
    ]
