# Generated by Django 5.1.4 on 2024-12-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_person_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='miesiac_dodany',
            new_name='month_added',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='imie',
            new_name='name',
        ),
    ]
