# Generated by Django 5.1.4 on 2025-01-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_miesiac_dodany_person_month_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='imie',
            new_name='name',
        ),
    ]
